[main]
start-unlocked=false
keypad=true
password-length=6
main-monitor=DSI-1
phone-pin=147147
pam-fallback=false

[tap-to-wake]
device-path=/dev/input/by-path/SET-ME-UP
verbose=false
timeout=500

[events]
on-lock-cmd=
on-unlock-cmd=
on-tap-cmd=

[profile]
image-path=
scale=128
rounding=64

[clock]
time-format=%H:%M
date-format=%a %d %b
